#!/usr/bin/env bash

set -euo pipefail

hosts_file=/etc/hosts
begin_block="# BEGIN DOCKER CONTAINERS"
end_block="# END DOCKER CONTAINERS"

if ! grep -Fxq "${begin_block}" "${hosts_file}"; then
  echo -e "\n${begin_block}\n${end_block}\n" >> "${hosts_file}"
fi

(echo "| container start |" && docker events) | \
while read event; do
  if [[ "${event}" == *" container start "* ]] || [[ "${event}" == *" network disconnect "* ]]; then
    hosts_file_tmp="$(mktemp)"
    docker container inspect -f '{{$ip := "#"}}{{range.NetworkSettings.Networks}}{{$ip = .IPAddress}}{{end}}{{$ip}} {{.Name}}' $(docker container ls -q) 2>/dev/null \
      | grep -v "^ " \
      | tr -d '/' \
      | sed -ne "/^${begin_block}$/ {p; r /dev/stdin" -e ":a; n; /^${end_block}$/ {p; b}; ba}; p" "${hosts_file}" \
      > "${hosts_file_tmp}" || true
    chmod 644 "${hosts_file_tmp}"
    mv "${hosts_file_tmp}" "${hosts_file}"
  fi
done

