#! /usr/bin/env bash

script_root=$(cd "${BASH_SOURCE[0]%/*}" && pwd -P)

if [ "$(id -u)" -ne 0 ]; then
  sudo "${0}" "${@}"
  exit ${?}
fi

install -o root -g root -m 0644 "${script_root}"/docker-update-hosts.service /etc/systemd/system
install -o root -g root -m 0755 "${script_root}"/docker-update-hosts /usr/local/bin

systemctl daemon-reload
systemctl enable docker-update-hosts.service
systemctl start docker-update-hosts.service

